### PR TITLE
Spool-Editing-Dialog: Auto weight/length feature

### PR DESCRIPTION
**Pull request by TiziG**
New functionality for the spool editing dialog. Let me know what you think!

### New Functionality:
- Filament weight input values get automatically converted from gram to mm and vice versa. (Requires valid diameter and density)
- A new dropdown select enables auto updating of different values. This allows for following calculations:
  - Calculate initial/remaining/used filament weight by measuring the combined filament+spool weight and defining the empty spool weight.
  - Calculate empty spool weight by measuring the initial combined filament+spool weight and defining the initial filament weight.

### UI Changes
- Split weight inputs into 3 categories: Filament, Spool, Combined
- Added inputs for combined weight
- Added auto calculation dropdown
- Added info texts for auto calculation and unit conversions
- Fixed overflow behavior of the editing dialog. Previously some inputs got covered by the gray button section from the bottom (on small screens).

### Implementation Details
The new logic is implemented solely in the dialog view model. The new input fields (for combined weight) are derived fields and do not get stored outside the view model (hence no db changes).

### Related Tickets
implements #202

### Screenshots
dialog

missing diameter

autofilament

dropdown

### CODE REVIEW

**Comment by TiziG** [comment]
@OllisGit 
Merge conflicts are now resolved.

The only debatable conflict was the css for the dialog min/max height. Both your version 1.5 and this PR tried to fix the height issues. I chose my solution, as it also prevents the dialog from becoming too high on large displays. Although I'm not quite sure if the now deleted #full-sized-box div had other side effects.

#### Solution in this PR:
[html](https://github.com/TiziG/OctoPrint-SpoolManager/blob/5a3f28f97cd5fb76a2e25795ebe9999f7428b708/octoprint_SpoolManager/templates/SpoolManager_dialog_editSpool.jinja2#L109-L110):
```
<div class="modal-body hack-flowbreak"  >
  <form  class="form-horizontal" id="spool-form" >
    ...
```
[css](https://github.com/TiziG/OctoPrint-SpoolManager/blob/5a3f28f97cd5fb76a2e25795ebe9999f7428b708/octoprint_SpoolManager/static/css/SpoolManager.css#L78-L80):
```
.hack-flowbreak {
  max-height: calc(100vh - 250px) !important;
}
```
#### Solution of Version 1.5:
*html*
```
  <div class="modal-body "  >
    <div class="full-sized-box">
      <form  class="form-horizontal" id="spool-form" >
        ...
```
*js*
```
self.spoolDialog.modal({
    minHeight: function() { return Math.max($.fn.modal.defaults.maxHeight() - 180, 250); },
    ...
})
```

**Comment by OllisGit** [comment]
Fyi: I will try your css solution...the  minHeight is taken from OP sourcecode I only adjust the maxheight, e.g. AboutDialog
```
            self.aboutDialog
                .modal({
                    minHeight: function () {
                        return Math.max($.fn.modal.defaults.maxHeight() - 80, 250);
                    }
                })
                .css({
                    "width": "auto",
                    "margin-left": function () {
                        return -($(this).width() / 2);
                    }
                });
```

**Comment by OllisGit** [comment]
Hi @TiziG,

I changed the ui a little bit (make it more compact). Smaller headers and replace all "Auto calculation prevents editing." with a single static note on top.

image
 
... I will change some other stuff (not related to this PR), so it will take a while when I release the next version.

**Comment by OllisGit** [comment]
Btw. which calc.mode should be the default one? and should this be stored in plugins-settings or in each spool?

**Comment by OllisGit** [comment]
Hi @TiziG,

your merge is now in the latest release. Thanks again, very helpful!

I changed some small things...e.g. remaining field is now in readonly mode. The value is only calculated.

Please test and give a feedback if you found some issues.

**Comment by TiziG** [comment]
Awesome, thanks for your work @OllisGit !
I'll check it out in the next few days.

**Pull request merged**
