### PR TITLE
Improve wording on confirmation dialog

### PR DESCRIPTION
**Pull request by ThomDietrich**
Hey,
minor detail indeed. I was always confused by the "anyway" at the end of the normal confirmation dialog. This fixes that. Feel free to further tweak the wording and/or merge directly.
Best!

### CODE REVIEW

**Comment by ThomDietrich** [comment]
@OllisGit anything you are unsure about? Let's not have stalebot hinder improvement ;)

**Comment by ThomDietrich** [comment]
Could you add one improvement while at it?

The Spool Manager Sidebar displays my spool as:
image
The dialog however only talks about "Sunlu Black". How about we add the material info "TPU-" to it?

**Comment by ThomDietrich** [comment]
Not stale. Waiting for response from @OllisGit

**Comment by OllisGit** [comment]
Hi @ThomDietrich,

thanks a lot for this PR, I appreciate it very much!
Will be in the next release.

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.
PSS. the stale-bot is now deactivated.

**Comment by OllisGit** [comment]
Hi @ThomDietrich,
implementation is in the latest release 1.3.0, thx again!

 The improvement of the "material-output" is now tracked in this issue #102

**Pull request closed without merging**
